// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// Factorial provides a mock function with given fields: n
func (_m *MockStorage) Factorial(n int64) (int64, error) {
	ret := _m.Called(n)

	if len(ret) == 0 {
		panic("no return value specified for Factorial")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (int64, error)); ok {
		return rf(n)
	}
	if rf, ok := ret.Get(0).(func(int64) int64); ok {
		r0 = rf(n)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(n)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_Factorial_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Factorial'
type MockStorage_Factorial_Call struct {
	*mock.Call
}

// Factorial is a helper method to define mock.On call
//   - n int64
func (_e *MockStorage_Expecter) Factorial(n interface{}) *MockStorage_Factorial_Call {
	return &MockStorage_Factorial_Call{Call: _e.mock.On("Factorial", n)}
}

func (_c *MockStorage_Factorial_Call) Run(run func(n int64)) *MockStorage_Factorial_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockStorage_Factorial_Call) Return(_a0 int64, _a1 error) *MockStorage_Factorial_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_Factorial_Call) RunAndReturn(run func(int64) (int64, error)) *MockStorage_Factorial_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
