// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package model

type UserConverterImpl struct{}

func (c *UserConverterImpl) ConvertUser(source User) UserDTO {
	var modelUserDTO UserDTO
	modelUserDTO.ID = source.ID
	modelUserDTO.Username = source.Username
	modelUserDTO.Email = source.Email
	modelUserDTO.FullName = FormatFullName(source)
	modelUserDTO.Active = source.IsActive
	return modelUserDTO
}
func (c *UserConverterImpl) ConvertUserList(source []User) []UserDTO {
	var modelUserDTOList []UserDTO
	if source != nil {
		modelUserDTOList = make([]UserDTO, len(source))
		for i := 0; i < len(source); i++ {
			modelUserDTOList[i] = c.ConvertUser(source[i])
		}
	}
	return modelUserDTOList
}
